### PR TITLE
Clean up the code to improve readability and add class description

### PR DESCRIPTION
**Pull request by tchanyaswad**
- Changed variable names to conform with PEP 8
- Added class description
- Re-organize the code to improve readability.

### CODE REVIEW

**Comment by tchanyaswad** [comment]
@mlopatka I'm not sure if you are notified of this PR, so I tag you here just in case. Could you please help review this PR? Thanks!

**Comment by prateek-mittal** [comment]
Thanks all, for updates to the code. One quick comment that comes to mind
is that the code can use some more comments. For example, every function
(and major code block) can have one higher level sentence about what the
function is about.

**Comment by tchanyaswad** [comment]
@prateek-mittal I agree. I will add this to the standing issue.

**Review by mlopatka — APPROVED** [review]
Looks good, reasonable changes to the unit testing.
One improvement could be to programmatically generate test data rather than import from a binary.

**Comment by mlopatka** [comment]
> @mlopatka I'm not sure if you are notified of this PR, so I tag you here just in case. Could you please help review this PR? Thanks!

@tchanyaswad thanks for flagging me :)

**Pull request merged**
